microservices:
  - name: auth
    image:
      repository: mohamedaziz599/auth
      tag: 123
    port: 3000
    env:
      - name: JWT_KEY
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_KEY
      - name: MONGO_URI
        value: mongodb://mongodb:27017/auth
      - name: RABBITMQ_URL
        valueFrom:
          secretKeyRef:
            name: rabbitmq-secret
            key: rabbitmq_url

  - name: client
    image:
      repository: mohamedaziz599/client
      tag: 123
    port: 3000
    env:
      - name: HOST
        value: "0.0.0.0"
      - name: JWT_KEY
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_KEY
      - name: MONGO_URI
        value: mongodb://mongodb:27017/client

  - name: orders
    image:
      repository: mohamedaziz599/orders
      tag: 123
    port: 3000
    env:
      - name: JWT_KEY
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_KEY
      - name: MONGO_URI
        value: mongodb://mongodb:27017/orders
      - name: RABBITMQ_URL
        valueFrom:
          secretKeyRef:
            name: rabbitmq-secret
            key: rabbitmq_url

  - name: payments
    image:
      repository: mohamedaziz599/payments
      tag: 123
    port: 3000
    env:
      - name: JWT_KEY
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_KEY
      - name: MONGO_URI
        value: mongodb://mongodb:27017/payments
      - name: RABBITMQ_URL
        valueFrom:
          secretKeyRef:
            name: rabbitmq-secret
            key: rabbitmq_url
      - name: STRIPE_KEY
        valueFrom:
          secretKeyRef:
            name: stripe-secret
            key: STRIPE_KEY

  - name: tickets
    image:
      repository: mohamedaziz599/tickets
      tag: 123
    port: 3000
    env:
      - name: JWT_KEY
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_KEY
      - name: MONGO_URI
        value: mongodb://mongodb:27017/tickets
      - name: RABBITMQ_URL
        valueFrom:
          secretKeyRef:
            name: rabbitmq-secret
            key: rabbitmq_url

  - name: expiration
    image:
      repository: mohamedaziz599/expiration
      tag: 123
    port: 3000
    env:
      - name: JWT_KEY
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_KEY
      - name: MONGO_URI
        value: mongodb://mongodb:27017/expiration
      - name: RABBITMQ_URL
        valueFrom:
          secretKeyRef:
            name: rabbitmq-secret
            key: rabbitmq_url

rabbitmq:
  enabled: true
  image: rabbitmq:3-management
  port: 5672
  managementPort: 15672

mongodb:
  enabled: true
  image: mongo:6
  port: 27017
