apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_KEY
      remoteRef:
        key: microservices/auth
        property: JWT_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: microservices/rabbitmq
        property: rabbitmq_url
    - secretKey: username
      remoteRef:
        key: microservices/rabbitmq
        property: username
    - secretKey: password
      remoteRef:
        key: microservices/rabbitmq
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stripe-secret
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: stripe-secret
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_KEY
      remoteRef:
        key: microservices/payments
        property: STRIPE_KEY
