{{- if and .Values.mongodb .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image | default "mongo:6" }}
          ports:
            - containerPort: {{ .Values.mongodb.port | default 27017 }}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port | default 27017 }}
      targetPort: {{ .Values.mongodb.port | default 27017 }}
{{- end }}
