{{- range .Values.microservices }}
{{- if eq .name "payments" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .port }}

          # 🔥 Variables d'environnement
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: MONGO_URI
              value: mongodb://mongodb:27017/payments

            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq_url

            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .port }}

{{- end }}
{{- end }}
