apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: YWRtaW4=
  password: U3Ryb25nUGFzc3dvcmQxMjM=
  rabbitmq_url: YW1xcDovL2FkbWluOlN0cm9uZ1Bhc3N3b3JkMTIzQHJhYmJpdG1xOjU2NzI=
